package org.marcelot;
// Generated 22/09/2020 18:52:05 by Hibernate Tools 5.4.18.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;


/**
 * Usuarios generated by hbm2java
 */
@Entity
public class Usuarios implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)

	private Integer id;
	private String nome;
	private String usuario;
	private String senha;
	private Integer versao;
	private String ativo;
	private Date dataCadastro;
	private byte[] imagem;
	private BigDecimal salario;
	private String celular;
	private Date nascimento;
	private Character sexo;
	private BigDecimal peso;
	private BigDecimal altura;
	private String sobreNome;
	private String corOlhos;
	private String corPele;
	private String endereco;

	public Usuarios() {
	}

	public Usuarios(String nome, String usuario) {
		this.nome = nome;
		this.usuario = usuario;
	}

	public Usuarios(String nome, String usuario, String senha, Integer versao, String ativo, Date dataCadastro,
			byte[] imagem, BigDecimal salario, String celular, Date nascimento, Character sexo, BigDecimal peso,
			BigDecimal altura, String sobreNome, String corOlhos, String corPele, String endereco) {
		this.nome = nome;
		this.usuario = usuario;
		this.senha = senha;
		this.versao = versao;
		this.ativo = ativo;
		this.dataCadastro = dataCadastro;
		this.imagem = imagem;
		this.salario = salario;
		this.celular = celular;
		this.nascimento = nascimento;
		this.sexo = sexo;
		this.peso = peso;
		this.altura = altura;
		this.sobreNome = sobreNome;
		this.corOlhos = corOlhos;
		this.corPele = corPele;
		this.endereco = endereco;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	public Integer getVersao() {
		return this.versao;
	}

	public void setVersao(Integer versao) {
		this.versao = versao;
	}

	public String getAtivo() {
		return this.ativo;
	}

	public void setAtivo(String ativo) {
		this.ativo = ativo;
	}

	public Date getDataCadastro() {
		return this.dataCadastro;
	}

	public void setDataCadastro(Date dataCadastro) {
		this.dataCadastro = dataCadastro;
	}

	public byte[] getImagem() {
		return this.imagem;
	}

	public void setImagem(byte[] imagem) {
		this.imagem = imagem;
	}

	public BigDecimal getSalario() {
		return this.salario;
	}

	public void setSalario(BigDecimal salario) {
		this.salario = salario;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public Date getNascimento() {
		return this.nascimento;
	}

	public void setNascimento(Date nascimento) {
		this.nascimento = nascimento;
	}

	public Character getSexo() {
		return this.sexo;
	}

	public void setSexo(Character sexo) {
		this.sexo = sexo;
	}

	public BigDecimal getPeso() {
		return this.peso;
	}

	public void setPeso(BigDecimal peso) {
		this.peso = peso;
	}

	public BigDecimal getAltura() {
		return this.altura;
	}

	public void setAltura(BigDecimal altura) {
		this.altura = altura;
	}

	public String getSobreNome() {
		return this.sobreNome;
	}

	public void setSobreNome(String sobreNome) {
		this.sobreNome = sobreNome;
	}

	public String getCorOlhos() {
		return this.corOlhos;
	}

	public void setCorOlhos(String corOlhos) {
		this.corOlhos = corOlhos;
	}

	public String getCorPele() {
		return this.corPele;
	}

	public void setCorPele(String corPele) {
		this.corPele = corPele;
	}

	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

}
